clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  phpcs:
    image: joomlaprojects/docker-phpcs
    commands:
      - echo $(date)
      - /root/.composer/vendor/bin/phpcs --report=full --encoding=utf-8 --extensions=php -p --standard=build/phpcs/Joomla .
      - echo $(date)

  javascript:
    image: joomlaprojects/docker-systemtests:latest
    commands:
      - echo $(date)
      - apt-get install nodejs npm
      - ln -s /usr/bin/nodejs /usr/bin/node
      - export DISPLAY=:0
      - Xvfb -screen 0 1024x768x24 -ac +extension GLX +render -noreset > /dev/null 2>&1 &
      - sleep 3
      - fluxbox  > /dev/null 2>&1 &
      - cd tests/javascript
      - npm install
      - cd ../..
      - tests/javascript/node_modules/karma/bin/karma start karma.conf.js --single-run
      - echo $(date)

  analysis3x:
    image: rips/rips-cli:1.2.1
    secrets:  [rips_username, rips_password]
    when:
      branch: staging
    commands:
      - export RIPS_BASE_URI='https://api.rips.joomla.org'
      - export RIPS_USERNAME=$RIPS_USERNAME
      - export RIPS_PASSWORD=$RIPS_PASSWORD
      - if [ $DRONE_REPO_OWNER != 'joomla' ]; then echo "The analysis check only run on the main repos"; exit 0; fi
      - rips-cli rips:scan:start -a 1 -t 1 -p $(pwd) -t 1 -R -k -T $DRONE_REPO_OWNER-$DRONE_BRANCH ||  { echo "Please contact the security team at security@joomla.org"; exit 1; }

  analysis4x:
    image: rips/rips-cli:1.2.1
    secrets:  [rips_username, rips_password]
    when:
      branch: 4.0-dev
    commands:
      - export RIPS_BASE_URI='https://api.rips.joomla.org'
      - export RIPS_USERNAME=$RIPS_USERNAME
      - export RIPS_PASSWORD=$RIPS_PASSWORD
      - if [ $DRONE_REPO_OWNER != 'joomla' ]; then echo "The analysis check only run on the main repos"; exit 0; fi
      - rips-cli rips:scan:start -a 3 -t 1 -p $(pwd) -t 1 -R -k -T $DRONE_REPO_OWNER-$DRONE_BRANCH ||  { echo "Please contact the security team at security@joomla.org"; exit 1; }

branches:
  exclude: [ l10n_* ]
